# Change these first
owner: AutohostAI # Your GitHub organization or username, where this repository lives
repo: AutohostAI # The name of this repository

sites:
  - name: Public API
    url: $URL_PUBLIC_API
    method: GET
    headers:
      - "X-Api-Key: $URL_PUBLIC_API_KEY"
  - name: Private API
    url: $URL_PRIVATE_API
  - name: SDK API
    url: $URL_SDK_API
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"type":"Security","level":"info","message":"upptime"}'
  - name: Dashboard
    url: $URL_DASHBOARD
  - name: Guest Portal
    url: $URL_GUEST_PORTAL
  - name: Dev Docs
    url: https://docs.autohost.ai
  - name: Threat Intel
    url: https://www.openreputationapi.com
  - name: Global Watchlist
    url: https://www.sanctionswatchlist.com
  - name: Tenant Evictions
    url: https://www.opentenantevictions.com
  - name: Marketing Website
    url: https://www.autohost.ai

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.autohost.dev
  # baseUrl: /upptime
  logoUrl: https://cdn.autohost.ai/logos/Icon/Autohost-icon-negative.svg
  name: Autohost Status
  introTitle: "Autohost Platform Status Page"
  introMessage: Health status monitor for the Autohost platform and services.
  navbar:
    - title: Docs
      href: https://docs.autohost.ai
    - title: Support
      href: https://www.autohost.ai/support

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
